name: Docker Image CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
 
env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # quay and ghcr logins for pushing image after testing
      # - name: Login to Quay Registry
      #   uses: docker/login-action@v1 
      #   with:
      #     registry: quay.io
      #     username: ${{ secrets.QUAY_USERNAME }}
      #     password: ${{ secrets.QUAY_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          Labels: |
            "runnumber=${GITHUB_RUN_ID}"
          secrets: |
            "MY_GITHUB_TOKEN=${{ secrets.MY_GITHUB_TOKEN }}"
          build-args: |
            "GITHUB_ID=${{ github.repository_owner }}"
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:latest
           
      # run tests using image from docker hub
      # - name: Run Tests
      #   run: make tests
      # copy multiplatform image from dockerhub to quay and ghcr
            # can push to all of these
            # quay.io/user/app:latest
            # quay.io/user/app:1.0.0
            # ghcr.io/user/app:latest
            # ghcr.io/user/app:1.0.0
      - name: Push Image to multiple registries
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src:  ghcr.io/${{ env.IMAGE_NAME }}:latest
          dst: |
            docker.io/${{ env.IMAGE_NAME }}:latest
